---
- name: restart-nginx
  become: yes
  docker_container:
    image: "nginx:{{ nginx_docker_version_tag }}"
    name: nginx
    volumes: "{{ exposed_volumes }}"
    ports: "{{ published_ports }}"
    exposed_ports: "{{ exposed_ports }}"
    state: 'stopped'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: nginx
  notify: start-nginx

- name: start-nginx
  become: yes
  docker_container:
    image: "nginx:{{ nginx_docker_version_tag }}"
    name: nginx
    volumes: "{{ exposed_volumes }}"
    ports: "{{ published_ports }}"
    exposed_ports: "{{ exposed_ports }}"
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: nginx